spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kioskdb
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis:
    type-aliases-package: com.aloha.kiosk.dto
    mapper-locations: classpath:mapper/*.xml

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html